<a href="https://colab.research.google.com/github/A23929/R-Programming/blob/main/22237_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Matrix operations

In [ ]:
# Create two 2x2 matrices.
matrix1 <- matrix(c(1,2,34,1), nrow = 2)
print(matrix1)

matrix2 <- matrix(c(5,-23,7,2), nrow = 2)
print(matrix2)

# Add the matrices.
result <- matrix1 + matrix2
cat("Result of addition:","\n")
print(result)

# Subtract the matrices
result <- matrix1 - matrix2
cat("Result of subtraction:","\n")
print(result)

     [,1] [,2]
[1,]    1   34
[2,]    2    1
     [,1] [,2]
[1,]    5    7
[2,]  -23    2
Result of addition 
     [,1] [,2]
[1,]    6   41
[2,]  -21    3
Result of subtraction 
     [,1] [,2]
[1,]   -4   27
[2,]   25   -1


In [ ]:
M = matrix(c(1,1,0,0,8,-3,-1,2), nrow=2,ncol=4,byrow = TRUE)
print(M) 
print(t(M))
t = M %*% t(M) #Matrix multiplication with transpose
print(t)

     [,1] [,2] [,3] [,4]
[1,]    1    1    0    0
[2,]    8   -3   -1    2
     [,1] [,2]
[1,]    1    8
[2,]    1   -3
[3,]    0   -1
[4,]    0    2
     [,1] [,2]
[1,]    2    5
[2,]    5   78


#### Control structures

In [ ]:
a <- 2
b <- 3
if(a<1)
    {
    b <- 32
} else if(a==1)
{
    b <- 9
} else
{
    b <- a
}

for(i in 1:a)
    print(i*2)

[1] 2
[1] 4


#### If else and for loop

In [ ]:
a <- c(2L,3.1,4,1,4.2,1,3,1,5,4.1)

In [ ]:
for(i in 1:10)
{
    if(is.integer(a[i]))
    
        a[i] = 0.0
    else
        next # Go to the next iteration 
    a[i] <- a[i]+1
    if(a[i]==2)
        break
} 
print(a)

 [1] 2.0 3.1 4.0 1.0 4.2 1.0 3.0 1.0 5.0 4.1


#### While loop

In [ ]:
i=0
while (i <= 3)
{ 
    print(i)
    i <- i + 1
}

[1] 0
[1] 1
[1] 2
[1] 3


#### Repeat

In [ ]:
v <- 1:4
i <-1
repeat{
    i <- i+1
    print(v[i])
    if(i==4)
        break
}

[1] 2
[1] 3
[1] 4
